import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import os
import joblib

# --- CONFIGURATION ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# Adjust this path to point to the file generated by the previous script
INPUT_FILE = os.path.abspath(os.path.join(BASE_DIR, "..", "..", "data", "final", "Delhi_Master_Dataset.csv"))
MODELS_DIR = os.path.join(BASE_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)

# --- THE EXPERT MODELS CONFIGURATION ---
# REMOVED: Rate_Trauma (Because accidents are random and cannot be predicted by weather)
EXPERTS = {
    'Rate_Vector': {
        'name': '🦟 Vector-Borne Model',
        'description': 'Predicts Dengue/Malaria based on Rain & Humidity',
        'features': ['Monthly_Avg_Temp', 'Rainfall_mm', 'Monthly_Avg_Humidity', 'dengue', 'fever', 'Rate_Vector']
    },
    'Rate_Respiratory': {
        'name': '🫁 Respiratory Model',
        'description': 'Predicts Asthma/TB based on AQI & Cold Weather',
        'features': ['Monthly_Avg_AQI', 'Days_Severe_AQI', 'Monthly_Avg_Temp', 'asthma', 'cough', 'cold', 'Rate_Respiratory']
    },
    'Rate_Water': {
        'name': '💧 Water-Borne Model',
        'description': 'Predicts Typhoid/Diarrhea based on Heat & Sanitation',
        # ADDED: 'Rainfall_Lag_2' to catch delayed water contamination effects
        'features': ['Monthly_Avg_Temp', 'Rainfall_mm', 'Rainfall_Lag_2', 'loose motion', 'vomiting', 'stomach pain', 'Rate_Water']
    }
}

def train_experts():
    print(f"Loading Data from {INPUT_FILE}...")
    try:
        df = pd.read_csv(INPUT_FILE)
    except FileNotFoundError:
        print("ERROR: Data file not found. Please run 'create_master_data.py' first!")
        return

    # --- NEW: FEATURE ENGINEERING (ADDING LAGS) ---
    print("⏳ Engineering Lag Features (Deep History)...")
    # Water contamination takes time. Rain today -> Groundwater bad in 2 months -> Sick people.
    df['Rainfall_Lag_2'] = df['Rainfall_mm'].shift(2)
    
    # Setup Dashboard Plot (1 Row, 3 Columns since we dropped Trauma)
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    axes = axes.flatten()
    
    results_summary = []

    print("\n🚀 STARTING TRAINING SESSION...")

    for idx, (target_col, config) in enumerate(EXPERTS.items()):
        print(f"\nTraining {config['name']}...")
        
        # 1. Target Shifting (Predict NEXT month)
        df['Target_Next_Month'] = df[target_col].shift(-1)
        
        # Drop NaN rows (created by shifting and lags)
        # We need to drop more rows now because of Lag_2
        clean_data = df.dropna(subset=['Target_Next_Month', 'Rainfall_Lag_2'] + config['features']).copy()

        # 2. Select Features
        X = clean_data[config['features']]
        y = clean_data['Target_Next_Month']

        # 3. Train/Test Split
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

        # 4. Train Model
        model = RandomForestRegressor(n_estimators=200, max_depth=5, random_state=42)
        model.fit(X_train, y_train)

        # 5. Save Model
        model_filename = os.path.join(MODELS_DIR, f"{target_col}_model.pkl")
        joblib.dump(model, model_filename)

        # 6. Evaluate
        preds = model.predict(X_test)
        mae = mean_absolute_error(y_test, preds)
        r2 = r2_score(y_test, preds)
        
        print(f"   -> MAE: {mae:.2f} (Avg error in cases/1k visits)")
        print(f"   -> R2 Score: {r2:.2f}")

        # 7. Visualization
        test_dates = clean_data.loc[X_test.index, 'Date']
        plot_df = pd.DataFrame({
            'Date': pd.to_datetime(test_dates),
            'Actual': y_test,
            'Predicted': preds
        }).sort_values(by='Date')

        ax = axes[idx]
        ax.plot(plot_df['Date'], plot_df['Actual'], color='gray', marker='o', alpha=0.6, label='Actual')
        ax.plot(plot_df['Date'], plot_df['Predicted'], color='blue', linestyle='--', linewidth=2, label='AI Forecast')
        
        ax.set_title(f"{config['name']}\n(MAE: ±{mae:.2f})", fontweight='bold')
        ax.legend()
        ax.grid(True, alpha=0.3)
        
        results_summary.append({
            'Model': config['name'],
            'MAE': mae,
            'R2': r2
        })

    # Save Dashboard
    plt.tight_layout()
    plt.savefig("Expert_Models_Dashboard.png")
    print("\n✅ Training Complete!")
    print("📊 Dashboard saved as 'Expert_Models_Dashboard.png'")

    # Print Summary Table
    print("\n--- FINAL PERFORMANCE REPORT ---")
    summary_df = pd.DataFrame(results_summary)
    print(summary_df)

if __name__ == "__main__":
    train_experts()